### PR TITLE
Handle KeyNotFoundException thrown from DictionaryPropertyProxy and DictionaryTypedPropertyProxy

### LINKED ISSUE #39: KeyNotFoundException not handled by "logErrorAction"
Hello!

We are using the `JsonPatchDocument.ApplyTo(TModel objectToApplyTo, IObjectAdapter adapter, Action<JsonPatchError>? logErrorAction)` method with the expectation that all operation errors will be sent to the `logErrorAction` handler. However, when an operation attempts to read a dictionary value with a missing key, the `KeyNotFoundException` bubbles up to our code.

The source of the exception appears to be `DictionaryTypedPropertyProxy<TKey, TValue>.GetValue()`/`DictionaryPropertyProxy.GetValue()`

We would like the library to handle that exception like other operation errors and pass it to `logErrorAction`. I have a fork with changes that I think will fix this issue. Let me know how to proceed, thanks!

Failing Patch Operation Examples:
```
{
    "op": "test",
    "path": "/DictionaryPropertyName/MissingKey",
    "value": "string"
}
```
```
{
    "op": "move",
    "from": "/DictionaryPropertyName/MissingKey",
    "path": "/someExistingProperty"
}
```
```
{
    "op": "copy",
    "from": "/DictionaryPropertyName/MissingKey",
    "path": "/someExistingProperty"
}
```

### PR DESCRIPTION
**Pull request by sbiot-aveva**
- Fixes #39
- Added Integration Tests to test scenario for generic and non-generic dictionaries

### CODE REVIEW

File: SystemTextJsonPatch/Internal/Proxies/DictionaryPropertyProxy.cs [hunk 1]
```diff
@@ -69,7 +77,7 @@ public Type PropertyType
 		{
 			get
 			{
-				var val = _dictionary[_propertyName];
+				var val = _dictionary.Contains(_propertyName) ? _dictionary[_propertyName] : null;
```
Comment (Havunen) [inline SystemTextJsonPatch/Internal/Proxies/DictionaryPropertyProxy.cs:80]: maybe this could use TryGetValue overload?

File: SystemTextJsonPatch/Internal/Proxies/DictionaryTypedPropertyProxy.cs [hunk 2]
```diff
@@ -16,9 +17,15 @@ internal DictionaryTypedPropertyProxy(IDictionary<TKey, TValue?> dictionary, TKe
 
 		public object? GetValue(object target)
 		{
-			var value = _dictionary[_propertyName];
-
-			return value;
+			try
+			{
+				var value = _dictionary[_propertyName];
```
Comment (Havunen) [inline SystemTextJsonPatch/Internal/Proxies/DictionaryTypedPropertyProxy.cs:22]: TryGetValue to avoid try catch?

**Review by Havunen — CHANGES_REQUESTED** [review]
Added some comments, otherwise LGTM

File: SystemTextJsonPatch/Internal/Proxies/DictionaryPropertyProxy.cs (hunk 1 above)
Comment (sbiot-aveva) [reply SystemTextJsonPatch/Internal/Proxies/DictionaryPropertyProxy.cs:80]: `IDictionary` doesn't have `TryGetValue`, so I went with the try-catch to keep the handling consistent between `DictionaryPropertyProxy` and `DictionaryTypedPropertyProxy`. But I can keep the try/catch here and use TryGetValue in the other file. Is that better?

Comment (Havunen) [reply SystemTextJsonPatch/Internal/Proxies/DictionaryPropertyProxy.cs:80]: Well I would like to avoid the try catch if possible, otherwise its ok.

File: SystemTextJsonPatch/Internal/Proxies/DictionaryTypedPropertyProxy.cs (hunk 2 above)
Comment (sbiot-aveva) [reply SystemTextJsonPatch/Internal/Proxies/DictionaryTypedPropertyProxy.cs]: Made the change!

File: SystemTextJsonPatch/Internal/Proxies/DictionaryPropertyProxy.cs (hunk 1 above)
Comment (sbiot-aveva) [reply SystemTextJsonPatch/Internal/Proxies/DictionaryPropertyProxy.cs:80]: I made the change in the other file

File: SystemTextJsonPatch/Internal/Proxies/DictionaryPropertyProxy.cs [hunk 3]
```diff
@@ -40,9 +42,15 @@ internal DictionaryPropertyProxy(IDictionary dictionary, string propertyName)
 
 		public object? GetValue(object target)
 		{
-			var value = _dictionary[_propertyName];
-
-			return value;
+			try
+			{
+				var value = _dictionary[_propertyName];
```
Comment (Havunen) [inline SystemTextJsonPatch/Internal/Proxies/DictionaryPropertyProxy.cs:47]: hmm, this still has try catch, well I can edit it after merging

File: SystemTextJsonPatch/JsonPatchDocument.cs [hunk 4]
```diff
@@ -167,11 +167,18 @@ public void ApplyTo(object objectToApplyTo, IObjectAdapter adapter, Action<JsonP
...
+				if (logErrorAction is null)
+				{
+					ErrorReporter.Default(jsonPatchError);
+
+					// As per JSON Patch spec if an operation results in error, further operations should not be executed.
+					break;
+				}
+				else
+				{
+					logErrorAction(jsonPatchError);
```
Comment (Havunen) [inline SystemTextJsonPatch/JsonPatchDocument.cs:180]: breka missing?

File: SystemTextJsonPatch/JsonPatchDocumentOfT.cs [hunk 5]
```diff
@@ -493,11 +493,18 @@ public void ApplyTo(TModel objectToApplyTo, IObjectAdapter adapter, Action<JsonP
...
+					ErrorReporter.Default(jsonPatchError);
 
-				// As per JSON Patch spec if an operation results in error, further operations should not be executed.
-				break;
+					// As per JSON Patch spec if an operation results in error, further operations should not be executed.
+					break;
+				}
+				else
+				{
+					logErrorAction(jsonPatchError);
```
Comment (Havunen) [inline SystemTextJsonPatch/JsonPatchDocumentOfT.cs:506]: same here, why was this changed? spec mentions to not proceed after encountering error

File: SystemTextJsonPatch/Internal/Proxies/DictionaryPropertyProxy.cs (hunk 3 above)
Comment (sbiot-aveva) [reply SystemTextJsonPatch/Internal/Proxies/DictionaryPropertyProxy.cs:47]: `IDictionary` does not have a `TryGetValue` method, so I couldn't make the suggested change in this file but I removed the try catch in DictionaryTypedPropertyProxy

File: SystemTextJsonPatch/JsonPatchDocumentOfT.cs (hunk 5 above)
Comment (sbiot-aveva) [reply SystemTextJsonPatch/JsonPatchDocumentOfT.cs:506]: I didn't put a break here to match the existing behavior. Currently (i.e. in the main branch): when `logErrorAction` is used and an operation fails the remaining operations proceed. I thought this was intentional but from your mention of the spec, it might be a bug?
For context, in our use case, this allows us to return all PATCH errors when we fail the request.

File: SystemTextJsonPatch/JsonPatchDocument.cs (hunk 4 above)
Comment (sbiot-aveva) [reply SystemTextJsonPatch/JsonPatchDocument.cs:180]: I didn't put a break here to match the existing behavior. More explanation in your other comment

File: SystemTextJsonPatch/Internal/Proxies/DictionaryPropertyProxy.cs (hunk 3 above)
Comment (Havunen) [reply SystemTextJsonPatch/Internal/Proxies/DictionaryPropertyProxy.cs:47]: We could instead change this to use Contains to check the existence of keys instead of wrapping it to try catch

**Comment by Havunen** [comment]
Lets keep the break in the error handling and use Contains to avoid try catch then this is good to be merged.

File: SystemTextJsonPatch/JsonPatchDocumentOfT.cs (hunk 5 above)
Comment (sbiot-aveva) [reply SystemTextJsonPatch/JsonPatchDocumentOfT.cs:506]: I can do that, but that means that the existing behavior does not follow RFC so should we also expect that to change?

Comment (Havunen) [reply SystemTextJsonPatch/JsonPatchDocumentOfT.cs:506]: Yes, we should follow spec. It makes no sense if one type of error goes through but others dont

File: SystemTextJsonPatch/JsonPatchDocument.cs (hunk 4 above)
Comment (sbiot-aveva) [reply SystemTextJsonPatch/JsonPatchDocument.cs]: reverted

File: SystemTextJsonPatch/JsonPatchDocumentOfT.cs (hunk 5 above)
Comment (sbiot-aveva) [reply SystemTextJsonPatch/JsonPatchDocumentOfT.cs]: got it, reverted.

Comment (sbiot-aveva) [reply SystemTextJsonPatch/JsonPatchDocumentOfT.cs]: Is it worth adding a test to document the inconsistency for now? Something like this:

Test Model:
```cs
public class TestModel
{
    public IDictionary<string, int> DictionaryOfStringToInteger { get; } = new Dictionary<string, int>();
}
```

For this example, I have two operations that should both result in a PATCH error:

Currently for any failing operation, `logErrorAction` will receive all operation errors (2 in this case) indicating that we don't stop on the first PATCH error
```json
[
    {
        "op": "test",
        "path": "/NonExistentProperty",
        "value": "string"
    },
    {
        "op": "test",
        "path": "/AnotherNonExistentProperty",
        "value": "string"
    }
]
```

But if the operation references a missing dictionary key, `logErrorAction` will only receive a single error
```json
[
    {
        "op": "test",
        "path": "/DictionaryOfStringToInteger/MissingKey",
        "value": "string"
    },
    {
        "op": "test",
        "path": "/DictionaryOfStringToInteger/AnotherMissingKey",
        "value": "string"
    }
]
```

Comment (Havunen) [reply SystemTextJsonPatch/JsonPatchDocumentOfT.cs]: It would be nice to unify this behavior. Its a breaking change so that is something what needs a major version bump...

**Comment by Havunen** [comment]
Thank you for your contribution!

File: SystemTextJsonPatch/JsonPatchDocumentOfT.cs (hunk 5 above)
Comment (Havunen) [reply SystemTextJsonPatch/JsonPatchDocumentOfT.cs]: ah, because it did not throw exceptions in earlier versions of .NET, it was changed in some recent version

**Comment by Havunen** [comment]
This change is now available in version 4.2.0
